#!/bin/bash

#SBATCH -p medium
#SBATCH -t 24:0:0
#SBATCH -c 4
#SBATCH --mem=8G
#SBATCH -o logs/step3_blast_%j.out
#SBATCH -e logs/step3_blast_%j.err


DATADIRLOCAL=$1
FASTAFILE=$2
GENOMICFASTA=$3
SPECIESNAME=$1

module load perl/5.24.0
module load blast/2.6.0+

date
echo "start"
echo "params:"
echo $1
echo $2
echo $3


echo "start step 3"
#perl scripts/3-blast_crisprs.pl -in data -fasta data/input/GCF_023101765.2_AGI-APGP_CSIRO_Sfru_2.0_genomic.fna -species SPECIESNAME
echo scripts/3-blast_crisprs.pl -datadir $DATADIRLOCAL -fasta $FASTAFILE  -genomicfasta $GENOMICFASTA  -species $SPECIESNAME
echo "...."
perl scripts/3-blast_crisprs.pl -datadir $DATADIRLOCAL -fasta $FASTAFILE  -genomicfasta $GENOMICFASTA  -species $SPECIESNAME

echo "done step 3"
echo "done"
date




