#!/bin/bash

#SBATCH -p priority                           
#SBATCH -t 1:00:0                             
#SBATCH --mem=16G                              
#SBATCH -o logs/step4_ote_%j.out              
#SBATCH -e logs/step4_ote_%j.err              

module load perl/5.24.0
date
echo "start"
echo "Params:"
echo $1

perl scripts/4-assign_ote_scores.pl -path $1

cut -f1,4  $1/output/ote_numbers.txt |sort |uniq -c |  perl -pe 's/^\s+//'| tr ' ' '\t' > $1/output/ote_numbers_count.txt

date
echo "done"
