#!/bin/bash

#SBATCH -p priority
#SBATCH -t 24:0:0
#SBATCH -c 4
#SBATCH --mem=8G
#SBATCH -o logs/step3_blast_%j.out
#SBATCH -e logs/step3_blast_%j.err

SPECIESNAME=$1
FASTAFILE=$2

module load perl/5.24.0
module load blast/2.6.0+

echo "start step 3"
#perl scripts/3-blast_crisprs.pl -in data -fasta data/input/GCF_023101765.2_AGI-APGP_CSIRO_Sfru_2.0_genomic.fna -species SPECIESNAME

perl scripts/3-blast_crisprs.pl -in data -fasta $FASTAFILE  -species $SPECIESNAME
echo "done step 3"





